#
# Makefile for CoreSight drivers.
#
obj-$(CONFIG_CORESIGHT_QCOM) += coresight.o
obj-$(CONFIG_CORESIGHT_QCOM_EVENT) += coresight-event.o
obj-$(CONFIG_CORESIGHT_QCOM_CTI) += coresight-cti.o
obj-$(CONFIG_CORESIGHT_QCOM_CSR) += coresight-csr.o
obj-$(CONFIG_CORESIGHT_QCOM_TMC) += coresight-tmc.o
obj-$(CONFIG_CORESIGHT_QCOM_FUNNEL) += coresight-funnel.o
obj-$(CONFIG_CORESIGHT_QCOM_REPLICATOR) += coresight-replicator.o
obj-$(CONFIG_CORESIGHT_QCOM_TPDA) += coresight-tpda.o
obj-$(CONFIG_CORESIGHT_QCOM_TPDM) += coresight-tpdm.o
obj-$(CONFIG_CORESIGHT_QCOM_STM) += coresight-stm.o
obj-$(CONFIG_CORESIGHT_QCOM_HWEVENT) += coresight-hwevent.o
obj-$(CONFIG_CORESIGHT_QCOM_ETMV4) += coresight-etmv4.o
obj-$(CONFIG_CORESIGHT_QCOM_REMOTE_ETM) += coresight-remote-etm.o
obj-$(CONFIG_OF_CORESIGHT) += of_coresight.o
obj-$(CONFIG_CORESIGHT_ACPI) += coresight-acpi.o
obj-$(CONFIG_CORESIGHT_PROPERTY) += coresight-property.o
obj-$(CONFIG_CORESIGHT_QCOM_SWEVENT) += coresight-imc-swevent.o
obj-$(CONFIG_CORESIGHT_QCOM_SWEVENT) += coresight-tz-swevent.o
obj-$(CONFIG_CORESIGHT_QCOM_SWEVENT) += coresight-asm.o
